### ISSUE TITLE
Missing steps to start sever in Readme.md or setup guide

### ISSUE THREAD

**Issue by sidforreal** [google/certificate-maker#2]
I have complete the setup for the project but won't be able to start the server or see the working application by any other mean.

**Comment by bluesomewhere** [comment]
Hi there! Thanks for flagging this issue. I've updated the README and setup scripts, which may resolve the issue for you if you're working on Mac OS X.

If not, please let me know and share some more details about your environment :-)

**Comment by bluesomewhere** [comment]
Gunna go ahead and close this issue for now, but please don't hesitate to reopen it if needed.
